# Generated by Django 2.0.6 on 2018-06-17 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pr1', '0002_auto_20180617_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zadanie',
            old_name='sd',
            new_name='slug',
        ),
    ]
